name: 'retailflow_transform'
version: '1.0.0'
config-version: 2

profile: 'retailflow'

model-paths: ["models"]
macro-paths: ["macros"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  retailflow_transform:
    staging:
      +materialized: view
    marts:
      +materialized: table
      +schema: marts